import work.lclpnet.build.task.GithubDeploymentTask

plugins {
    alias(libs.plugins.fabric.loom)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.utils)
    alias(libs.plugins.modrinth.minotaur)
}

Properties props = buildUtils.loadProperties('publish.properties')

version = "${project.mod_version}+${libs.versions.minecraft.get()}"
group = project.maven_group

def modId = project.mod_id
def javaVersion = libs.versions.java.get().toInteger()

base {
    archivesName = modId
}

repositories {
    mavenCentral()

    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        illwalls {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    accessWidenerPath = file("src/main/resources/illwalls.accesswidener")
}

dependencies {
    minecraft(libs.minecraft)
    implementation(libs.fabric.loader)
    implementation(libs.fabric.api)

    def includeImpl = { dep ->
        include(dep)
        implementation(dep)
    }

    includeImpl(libs.kibu.hook.api)
    includeImpl(libs.kibu.hooks)
    includeImpl(libs.kibu.schematic.fabric)
    includeImpl(libs.kibu.access.lib)

    if (project.hasProperty('enable_sodium')) {
        implementation(libs.sodium)
    }

    if (project.hasProperty('enable_iris')) {
        implementation(libs.iris)
        implementation(libs.jcpp)
        implementation(libs.glsl.transformer)
        implementation(libs.antlr4.runtime)
    }

    implementation(libs.jsr305)

    includeImpl(libs.kibu.schematic.api)
    includeImpl(libs.kibu.nbt.api)

    testImplementation(libs.fabric.loader.junit)
    testImplementation(libs.junit.jupiter.api)
    testImplementation(libs.junit.jupiter.params)
    testRuntimeOnly(libs.junit.jupiter.engine)
}

test {
    useJUnitPlatform()
}

configurations {
    testCompileClasspath.extendsFrom(minecraftCommonNamedCompile)
    testRuntimeClasspath.extendsFrom(minecraftCommonNamedRuntime)
}

processResources {
    def tokens = [
            "version": project.version.toString(),
            "loader_version": libs.versions.fabric.loader.get(),
            "minecraft_compat": project.minecraft_compat,
            "java_version": javaVersion.toString()
    ]

    inputs.properties(tokens)

    filesMatching("fabric.mod.json") {
        expand(tokens)
    }

    filesMatching("*.mixins.json") {
        filter(ReplaceTokens, beginToken: '${', endToken: '}', tokens: tokens)
    }
}

tasks.withType(JavaCompile).configureEach {
	it.options.release.convention(javaVersion)
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] Illusory Walls $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

modrinth {
    token = env.get("MODRINTH_TOKEN")

    projectId = "illusory-walls"
    versionName = "[${libs.versions.minecraft.get()}] Illusory Walls $project.version"
    versionType = "release"
    uploadFile = jar

    dependencies {
        required.project "fabric-api"
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.project.base.archivesName.get()

            from components.java

            pom {
                name = 'Illusory Walls'
                description = 'A Fabric mod to add illusory walls to Minecraft'
            }
        }
    }

    buildUtils.setupPublishRepository(repositories, props)
}