# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.6-rc1
yarn_mappings=1.21.6-rc1+build.1
loader_version=0.16.14
loom_version=1.10-SNAPSHOT
mod_version=0.2.1

# Mod Properties
maven_group=work.lclpnet.mods
archives_base_name=illusory-walls

# Dependencies
fabric_version=0.126.1+1.21.6
kibu_nbt_api_version=0.6.0
kibu_schematic_api_version=0.10.1
kibu_schematic_fabric_version=0.14.0+1.21.6-rc1
kibu_hook_api_version=1.4.0
kibu_hooks_version=0.60.0+1.21.6-rc1
kibu_access_lib_version=0.16.0+1.21.6-rc1

# optional dependencies
# sodium_version=mc1.21.5-0.6.12-fabric
# iris_version=1.8.10+1.21.5-fabric