# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
maven_group=work.lclpnet.mods
mod_id=illusory-walls
mod_version=0.2.1

minecraft_compat=26.1

# Dependencies
fabric_version=0.147.0+26.1.2
kibu_nbt_api_version=0.6.0
kibu_schematic_api_version=0.10.1
kibu_schematic_fabric_version=0.14.0+26.1
kibu_hook_api_version=1.4.0
kibu_hooks_version=0.64.1+26.1
kibu_access_lib_version=0.17.0+26.1

# optional dependencies
sodium_version=mc26.1.2-0.8.10-fabric
iris_version=1.10.9+26.1-fabric